# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\WorkSpace\eric4\stockii\stockUI\UI\MainWindow.ui'
#
# Created: Sun Sep 14 16:14:13 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(931, 617)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_11.addWidget(self.label_2)
        self.startDateEdit = QtGui.QDateEdit(self.groupBox_4)
        self.startDateEdit.setCalendarPopup(True)
        self.startDateEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.startDateEdit.setObjectName(_fromUtf8("startDateEdit"))
        self.horizontalLayout_11.addWidget(self.startDateEdit)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_11.addWidget(self.label_3)
        self.endDateEdit = QtGui.QDateEdit(self.groupBox_4)
        self.endDateEdit.setCalendarPopup(True)
        self.endDateEdit.setDate(QtCore.QDate(2014, 12, 30))
        self.endDateEdit.setObjectName(_fromUtf8("endDateEdit"))
        self.horizontalLayout_11.addWidget(self.endDateEdit)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.daySumRadio = QtGui.QRadioButton(self.groupBox_4)
        self.daySumRadio.setChecked(True)
        self.daySumRadio.setObjectName(_fromUtf8("daySumRadio"))
        self.verticalLayout_2.addWidget(self.daySumRadio)
        self.weekSumRadio = QtGui.QRadioButton(self.groupBox_4)
        self.weekSumRadio.setObjectName(_fromUtf8("weekSumRadio"))
        self.verticalLayout_2.addWidget(self.weekSumRadio)
        self.monthSumRadio = QtGui.QRadioButton(self.groupBox_4)
        self.monthSumRadio.setObjectName(_fromUtf8("monthSumRadio"))
        self.verticalLayout_2.addWidget(self.monthSumRadio)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.typeCombo = QtGui.QComboBox(self.groupBox_4)
        self.typeCombo.setObjectName(_fromUtf8("typeCombo"))
        self.horizontalLayout_12.addWidget(self.typeCombo)
        self.numCombo = QtGui.QComboBox(self.groupBox_4)
        self.numCombo.setObjectName(_fromUtf8("numCombo"))
        self.horizontalLayout_12.addWidget(self.numCombo)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.queryBtn = QtGui.QPushButton(self.groupBox_4)
        self.queryBtn.setObjectName(_fromUtf8("queryBtn"))
        self.horizontalLayout_13.addWidget(self.queryBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.cmpDateEdit1 = QtGui.QDateEdit(self.groupBox_5)
        self.cmpDateEdit1.setCalendarPopup(True)
        self.cmpDateEdit1.setObjectName(_fromUtf8("cmpDateEdit1"))
        self.horizontalLayout_6.addWidget(self.cmpDateEdit1)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.cmpDateEdit2 = QtGui.QDateEdit(self.groupBox_5)
        self.cmpDateEdit2.setCalendarPopup(True)
        self.cmpDateEdit2.setObjectName(_fromUtf8("cmpDateEdit2"))
        self.horizontalLayout_6.addWidget(self.cmpDateEdit2)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.cmpMethCombo = QtGui.QComboBox(self.groupBox_5)
        self.cmpMethCombo.setObjectName(_fromUtf8("cmpMethCombo"))
        self.horizontalLayout_5.addWidget(self.cmpMethCombo)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.cmpTypeCombo = QtGui.QComboBox(self.groupBox_5)
        self.cmpTypeCombo.setObjectName(_fromUtf8("cmpTypeCombo"))
        self.horizontalLayout_7.addWidget(self.cmpTypeCombo)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setText(_fromUtf8(""))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.calculateBtn = QtGui.QPushButton(self.groupBox_5)
        self.calculateBtn.setObjectName(_fromUtf8("calculateBtn"))
        self.horizontalLayout_10.addWidget(self.calculateBtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(self.centralWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableView = FreezeTableWidget(self.groupBox)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout_3.addWidget(self.tableView)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.tb1_headBtn = QtGui.QPushButton(self.groupBox)
        self.tb1_headBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.tb1_headBtn.setObjectName(_fromUtf8("tb1_headBtn"))
        self.horizontalLayout.addWidget(self.tb1_headBtn)
        self.tb1_upBtn = QtGui.QPushButton(self.groupBox)
        self.tb1_upBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.tb1_upBtn.setObjectName(_fromUtf8("tb1_upBtn"))
        self.horizontalLayout.addWidget(self.tb1_upBtn)
        self.tb1_curPageLabel = QtGui.QLabel(self.groupBox)
        self.tb1_curPageLabel.setObjectName(_fromUtf8("tb1_curPageLabel"))
        self.horizontalLayout.addWidget(self.tb1_curPageLabel)
        self.tb1_downBtn = QtGui.QPushButton(self.groupBox)
        self.tb1_downBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.tb1_downBtn.setObjectName(_fromUtf8("tb1_downBtn"))
        self.horizontalLayout.addWidget(self.tb1_downBtn)
        self.tb1_lastBtn = QtGui.QPushButton(self.groupBox)
        self.tb1_lastBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.tb1_lastBtn.setObjectName(_fromUtf8("tb1_lastBtn"))
        self.horizontalLayout.addWidget(self.tb1_lastBtn)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tableView_2 = FreezeTableWidget(self.groupBox_2)
        self.tableView_2.setObjectName(_fromUtf8("tableView_2"))
        self.verticalLayout_4.addWidget(self.tableView_2)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.tb2_headBtn = QtGui.QPushButton(self.groupBox_2)
        self.tb2_headBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.tb2_headBtn.setObjectName(_fromUtf8("tb2_headBtn"))
        self.horizontalLayout_14.addWidget(self.tb2_headBtn)
        self.tb2_upBtn = QtGui.QPushButton(self.groupBox_2)
        self.tb2_upBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.tb2_upBtn.setObjectName(_fromUtf8("tb2_upBtn"))
        self.horizontalLayout_14.addWidget(self.tb2_upBtn)
        self.tb2_curPageLabel = QtGui.QLabel(self.groupBox_2)
        self.tb2_curPageLabel.setObjectName(_fromUtf8("tb2_curPageLabel"))
        self.horizontalLayout_14.addWidget(self.tb2_curPageLabel)
        self.tb2_downBtn = QtGui.QPushButton(self.groupBox_2)
        self.tb2_downBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.tb2_downBtn.setObjectName(_fromUtf8("tb2_downBtn"))
        self.horizontalLayout_14.addWidget(self.tb2_downBtn)
        self.tb2_lastBtn = QtGui.QPushButton(self.groupBox_2)
        self.tb2_lastBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.tb2_lastBtn.setObjectName(_fromUtf8("tb2_lastBtn"))
        self.horizontalLayout_14.addWidget(self.tb2_lastBtn)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.groupBox_3 = QtGui.QGroupBox(self.splitter_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tableView_3 = FreezeTableWidget(self.groupBox_3)
        self.tableView_3.setObjectName(_fromUtf8("tableView_3"))
        self.gridLayout_4.addWidget(self.tableView_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.splitter_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 931, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        MainWindow.setMenuBar(self.menuBar)
        self.groupView = QtGui.QDockWidget(MainWindow)
        self.groupView.setObjectName(_fromUtf8("groupView"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.listWidget = QtGui.QListWidget(self.dockWidgetContents)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_5.addWidget(self.listWidget)
        self.groupView.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.groupView)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_addGroup = QtGui.QAction(MainWindow)
        self.action_addGroup.setObjectName(_fromUtf8("action_addGroup"))
        self.action_editGroup = QtGui.QAction(MainWindow)
        self.action_editGroup.setObjectName(_fromUtf8("action_editGroup"))
        self.action_showGroupView = QtGui.QAction(MainWindow)
        self.action_showGroupView.setCheckable(True)
        self.action_showGroupView.setObjectName(_fromUtf8("action_showGroupView"))
        self.action_deleteGroup = QtGui.QAction(MainWindow)
        self.action_deleteGroup.setObjectName(_fromUtf8("action_deleteGroup"))
        self.menu_2.addAction(self.action)
        self.menu_2.addAction(self.action_showGroupView)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "原始数据筛选", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "开始日期：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "结束日期：", None, QtGui.QApplication.UnicodeUTF8))
        self.daySumRadio.setText(QtGui.QApplication.translate("MainWindow", "日和", None, QtGui.QApplication.UnicodeUTF8))
        self.weekSumRadio.setText(QtGui.QApplication.translate("MainWindow", "周和", None, QtGui.QApplication.UnicodeUTF8))
        self.monthSumRadio.setText(QtGui.QApplication.translate("MainWindow", "月和", None, QtGui.QApplication.UnicodeUTF8))
        self.queryBtn.setText(QtGui.QApplication.translate("MainWindow", "查询", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "计算筛选", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "比较日期：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "——", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "比较方法", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "比较指标：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "结果筛选：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", ">=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "<=", None, QtGui.QApplication.UnicodeUTF8))
        self.calculateBtn.setText(QtGui.QApplication.translate("MainWindow", "计算", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "原始数据：", None, QtGui.QApplication.UnicodeUTF8))
        self.tb1_headBtn.setText(QtGui.QApplication.translate("MainWindow", "首页", None, QtGui.QApplication.UnicodeUTF8))
        self.tb1_upBtn.setText(QtGui.QApplication.translate("MainWindow", "上页", None, QtGui.QApplication.UnicodeUTF8))
        self.tb1_curPageLabel.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.tb1_downBtn.setText(QtGui.QApplication.translate("MainWindow", "下页", None, QtGui.QApplication.UnicodeUTF8))
        self.tb1_lastBtn.setText(QtGui.QApplication.translate("MainWindow", "尾页", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "n日数据", None, QtGui.QApplication.UnicodeUTF8))
        self.tb2_headBtn.setText(QtGui.QApplication.translate("MainWindow", "首页", None, QtGui.QApplication.UnicodeUTF8))
        self.tb2_upBtn.setText(QtGui.QApplication.translate("MainWindow", "上页", None, QtGui.QApplication.UnicodeUTF8))
        self.tb2_curPageLabel.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.tb2_downBtn.setText(QtGui.QApplication.translate("MainWindow", "下页", None, QtGui.QApplication.UnicodeUTF8))
        self.tb2_lastBtn.setText(QtGui.QApplication.translate("MainWindow", "尾页", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "计算结果", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "文件", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "显示", None, QtGui.QApplication.UnicodeUTF8))
        self.groupView.setWindowTitle(QtGui.QApplication.translate("MainWindow", "股票筛选", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "分组1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listWidget.item(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "分组2", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.action.setText(QtGui.QApplication.translate("MainWindow", "设置列", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addGroup.setText(QtGui.QApplication.translate("MainWindow", "添加分组", None, QtGui.QApplication.UnicodeUTF8))
        self.action_editGroup.setText(QtGui.QApplication.translate("MainWindow", "编辑分组", None, QtGui.QApplication.UnicodeUTF8))
        self.action_showGroupView.setText(QtGui.QApplication.translate("MainWindow", "股票筛选", None, QtGui.QApplication.UnicodeUTF8))
        self.action_deleteGroup.setText(QtGui.QApplication.translate("MainWindow", "删除分组", None, QtGui.QApplication.UnicodeUTF8))

from freezetablewidget import FreezeTableWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

