# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\WorkSpace\eric4\stockii\stockii_client\UI\StockMain.ui'
#
# Created: Sun Nov 02 15:35:00 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1227, 806)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.listWidget = QtGui.QListWidget(self.centralWidget)
        self.listWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout_20.addWidget(self.listWidget)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_11.addWidget(self.label_2)
        self.startDateEdit = QtGui.QDateEdit(self.groupBox_4)
        self.startDateEdit.setCalendarPopup(True)
        self.startDateEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.startDateEdit.setObjectName(_fromUtf8("startDateEdit"))
        self.horizontalLayout_11.addWidget(self.startDateEdit)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_11.addWidget(self.label_3)
        self.endDateEdit = QtGui.QDateEdit(self.groupBox_4)
        self.endDateEdit.setCalendarPopup(True)
        self.endDateEdit.setDate(QtCore.QDate(2014, 12, 30))
        self.endDateEdit.setObjectName(_fromUtf8("endDateEdit"))
        self.horizontalLayout_11.addWidget(self.endDateEdit)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        self.queryBtn = QtGui.QPushButton(self.groupBox_4)
        self.queryBtn.setObjectName(_fromUtf8("queryBtn"))
        self.horizontalLayout_13.addWidget(self.queryBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.srcTableWidget = MyTable(self.groupBox)
        self.srcTableWidget.setObjectName(_fromUtf8("srcTableWidget"))
        self.verticalLayout_3.addWidget(self.srcTableWidget)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_18.addWidget(self.label_11)
        self.startDateEdit_2 = QtGui.QDateEdit(self.groupBox_6)
        self.startDateEdit_2.setCalendarPopup(True)
        self.startDateEdit_2.setDate(QtCore.QDate(2000, 1, 1))
        self.startDateEdit_2.setObjectName(_fromUtf8("startDateEdit_2"))
        self.horizontalLayout_18.addWidget(self.startDateEdit_2)
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_18.addWidget(self.label_12)
        self.endDateEdit_2 = QtGui.QDateEdit(self.groupBox_6)
        self.endDateEdit_2.setCalendarPopup(True)
        self.endDateEdit_2.setDate(QtCore.QDate(2014, 12, 30))
        self.endDateEdit_2.setObjectName(_fromUtf8("endDateEdit_2"))
        self.horizontalLayout_18.addWidget(self.endDateEdit_2)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.daySumRadio = QtGui.QRadioButton(self.groupBox_6)
        self.daySumRadio.setChecked(True)
        self.daySumRadio.setObjectName(_fromUtf8("daySumRadio"))
        self.verticalLayout_2.addWidget(self.daySumRadio)
        self.weekSumRadio = QtGui.QRadioButton(self.groupBox_6)
        self.weekSumRadio.setObjectName(_fromUtf8("weekSumRadio"))
        self.verticalLayout_2.addWidget(self.weekSumRadio)
        self.monthSumRadio = QtGui.QRadioButton(self.groupBox_6)
        self.monthSumRadio.setObjectName(_fromUtf8("monthSumRadio"))
        self.verticalLayout_2.addWidget(self.monthSumRadio)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.typeCombo = QtGui.QComboBox(self.groupBox_6)
        self.typeCombo.setObjectName(_fromUtf8("typeCombo"))
        self.horizontalLayout_12.addWidget(self.typeCombo)
        self.numCombo = QtGui.QComboBox(self.groupBox_6)
        self.numCombo.setObjectName(_fromUtf8("numCombo"))
        self.horizontalLayout_12.addWidget(self.numCombo)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_12)
        self.sumTypeCombo = QtGui.QComboBox(self.groupBox_6)
        self.sumTypeCombo.setObjectName(_fromUtf8("sumTypeCombo"))
        self.horizontalLayout_19.addWidget(self.sumTypeCombo)
        self.queryBtn_2 = QtGui.QPushButton(self.groupBox_6)
        self.queryBtn_2.setObjectName(_fromUtf8("queryBtn_2"))
        self.horizontalLayout_19.addWidget(self.queryBtn_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout_19)
        self.gridLayout_6.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.sumTableWidget = MyTable(self.groupBox_2)
        self.sumTableWidget.setObjectName(_fromUtf8("sumTableWidget"))
        self.verticalLayout_7.addWidget(self.sumTableWidget)
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.startDateEdit_3 = QtGui.QDateEdit(self.groupBox_5)
        self.startDateEdit_3.setCalendarPopup(True)
        self.startDateEdit_3.setObjectName(_fromUtf8("startDateEdit_3"))
        self.horizontalLayout_6.addWidget(self.startDateEdit_3)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.endDateEdit_3 = QtGui.QDateEdit(self.groupBox_5)
        self.endDateEdit_3.setCalendarPopup(True)
        self.endDateEdit_3.setDate(QtCore.QDate(2014, 1, 1))
        self.endDateEdit_3.setObjectName(_fromUtf8("endDateEdit_3"))
        self.horizontalLayout_6.addWidget(self.endDateEdit_3)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.cmpMethCombo = QtGui.QComboBox(self.groupBox_5)
        self.cmpMethCombo.setObjectName(_fromUtf8("cmpMethCombo"))
        self.horizontalLayout_5.addWidget(self.cmpMethCombo)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.cmpTypeCombo = QtGui.QComboBox(self.groupBox_5)
        self.cmpTypeCombo.setObjectName(_fromUtf8("cmpTypeCombo"))
        self.horizontalLayout_7.addWidget(self.cmpTypeCombo)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.smallValueEdit = QtGui.QLineEdit(self.groupBox_5)
        self.smallValueEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.smallValueEdit.setObjectName(_fromUtf8("smallValueEdit"))
        self.horizontalLayout_2.addWidget(self.smallValueEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.bigValueEdit = QtGui.QLineEdit(self.groupBox_5)
        self.bigValueEdit.setText(_fromUtf8(""))
        self.bigValueEdit.setObjectName(_fromUtf8("bigValueEdit"))
        self.horizontalLayout_3.addWidget(self.bigValueEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.calculateBtn = QtGui.QPushButton(self.groupBox_5)
        self.calculateBtn.setObjectName(_fromUtf8("calculateBtn"))
        self.horizontalLayout_10.addWidget(self.calculateBtn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.calcTableWidget = MyTable(self.groupBox_3)
        self.calcTableWidget.setObjectName(_fromUtf8("calcTableWidget"))
        self.gridLayout_4.addWidget(self.calcTableWidget, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_20.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout_20, 0, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(self.centralWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.gridLayout_2.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.showGroupBtn = QtGui.QPushButton(self.centralWidget)
        self.showGroupBtn.setMaximumSize(QtCore.QSize(100, 20))
        self.showGroupBtn.setCheckable(True)
        self.showGroupBtn.setObjectName(_fromUtf8("showGroupBtn"))
        self.horizontalLayout_17.addWidget(self.showGroupBtn)
        self.classifyBtn = QtGui.QPushButton(self.centralWidget)
        self.classifyBtn.setMaximumSize(QtCore.QSize(100, 20))
        self.classifyBtn.setCheckable(True)
        self.classifyBtn.setObjectName(_fromUtf8("classifyBtn"))
        self.horizontalLayout_17.addWidget(self.classifyBtn)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_17, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1227, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_addGroup = QtGui.QAction(MainWindow)
        self.action_addGroup.setObjectName(_fromUtf8("action_addGroup"))
        self.action_editGroup = QtGui.QAction(MainWindow)
        self.action_editGroup.setObjectName(_fromUtf8("action_editGroup"))
        self.action_showGroupView = QtGui.QAction(MainWindow)
        self.action_showGroupView.setCheckable(True)
        self.action_showGroupView.setObjectName(_fromUtf8("action_showGroupView"))
        self.action_deleteGroup = QtGui.QAction(MainWindow)
        self.action_deleteGroup.setObjectName(_fromUtf8("action_deleteGroup"))
        self.menu_2.addAction(self.action)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "分组1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listWidget.item(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "分组2", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "原始数据筛选", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "开始日期：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "结束日期：", None, QtGui.QApplication.UnicodeUTF8))
        self.queryBtn.setText(QtGui.QApplication.translate("MainWindow", "查询", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "原始数据：", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "原始数据", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "n日和筛选", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "开始日期：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "结束日期：", None, QtGui.QApplication.UnicodeUTF8))
        self.daySumRadio.setText(QtGui.QApplication.translate("MainWindow", "日和", None, QtGui.QApplication.UnicodeUTF8))
        self.weekSumRadio.setText(QtGui.QApplication.translate("MainWindow", "周和", None, QtGui.QApplication.UnicodeUTF8))
        self.monthSumRadio.setText(QtGui.QApplication.translate("MainWindow", "月和", None, QtGui.QApplication.UnicodeUTF8))
        self.queryBtn_2.setText(QtGui.QApplication.translate("MainWindow", "查询", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "n日数据", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "n日和", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "计算筛选", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "比较日期：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "——", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "比较方法", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "比较指标：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "结果筛选：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", ">=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "<=", None, QtGui.QApplication.UnicodeUTF8))
        self.calculateBtn.setText(QtGui.QApplication.translate("MainWindow", "计算", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "计算结果", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "自定义计算", None, QtGui.QApplication.UnicodeUTF8))
        self.showGroupBtn.setText(QtGui.QApplication.translate("MainWindow", "自选", None, QtGui.QApplication.UnicodeUTF8))
        self.classifyBtn.setText(QtGui.QApplication.translate("MainWindow", "版块▲", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "文件", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "显示", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "设置列", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addGroup.setText(QtGui.QApplication.translate("MainWindow", "添加分组", None, QtGui.QApplication.UnicodeUTF8))
        self.action_editGroup.setText(QtGui.QApplication.translate("MainWindow", "编辑分组", None, QtGui.QApplication.UnicodeUTF8))
        self.action_showGroupView.setText(QtGui.QApplication.translate("MainWindow", "股票筛选", None, QtGui.QApplication.UnicodeUTF8))
        self.action_deleteGroup.setText(QtGui.QApplication.translate("MainWindow", "删除分组", None, QtGui.QApplication.UnicodeUTF8))

from MyTable import MyTable

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

