# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\WorkSpace\eric4\stockii\stockii_client\UI\StockMain.ui'
#
# Created: Sun Dec 14 16:45:12 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1227, 806)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter_2 = QtGui.QSplitter(self.centralWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.splitter_3 = QtGui.QSplitter(self.centralWidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.widget = QtGui.QWidget(self.splitter_3)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.listWidget = QtGui.QListWidget(self.widget)
        self.listWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout_20.addWidget(self.listWidget)
        self.tabWidget = QtGui.QTabWidget(self.widget)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_11.addWidget(self.label_2)
        self.startDateEdit_1 = QtGui.QDateEdit(self.groupBox_4)
        self.startDateEdit_1.setDate(QtCore.QDate(2000, 1, 1))
        self.startDateEdit_1.setCalendarPopup(True)
        self.startDateEdit_1.setObjectName(_fromUtf8("startDateEdit_1"))
        self.horizontalLayout_11.addWidget(self.startDateEdit_1)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_11.addWidget(self.label_3)
        self.endDateEdit_1 = QtGui.QDateEdit(self.groupBox_4)
        self.endDateEdit_1.setDate(QtCore.QDate(2014, 12, 30))
        self.endDateEdit_1.setCalendarPopup(True)
        self.endDateEdit_1.setObjectName(_fromUtf8("endDateEdit_1"))
        self.horizontalLayout_11.addWidget(self.endDateEdit_1)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        self.queryBtn = QtGui.QPushButton(self.groupBox_4)
        self.queryBtn.setObjectName(_fromUtf8("queryBtn"))
        self.horizontalLayout_13.addWidget(self.queryBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.srcTableWidget = MyTable(self.groupBox)
        self.srcTableWidget.setObjectName(_fromUtf8("srcTableWidget"))
        self.verticalLayout_3.addWidget(self.srcTableWidget)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_18.addWidget(self.label_11)
        self.startDateEdit_2 = QtGui.QDateEdit(self.groupBox_6)
        self.startDateEdit_2.setDate(QtCore.QDate(2000, 1, 1))
        self.startDateEdit_2.setCalendarPopup(True)
        self.startDateEdit_2.setObjectName(_fromUtf8("startDateEdit_2"))
        self.horizontalLayout_18.addWidget(self.startDateEdit_2)
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_18.addWidget(self.label_12)
        self.endDateEdit_2 = QtGui.QDateEdit(self.groupBox_6)
        self.endDateEdit_2.setDate(QtCore.QDate(2014, 12, 30))
        self.endDateEdit_2.setCalendarPopup(True)
        self.endDateEdit_2.setObjectName(_fromUtf8("endDateEdit_2"))
        self.horizontalLayout_18.addWidget(self.endDateEdit_2)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.daySumRadio = QtGui.QRadioButton(self.groupBox_6)
        self.daySumRadio.setChecked(True)
        self.daySumRadio.setObjectName(_fromUtf8("daySumRadio"))
        self.verticalLayout_2.addWidget(self.daySumRadio)
        self.weekSumRadio = QtGui.QRadioButton(self.groupBox_6)
        self.weekSumRadio.setObjectName(_fromUtf8("weekSumRadio"))
        self.verticalLayout_2.addWidget(self.weekSumRadio)
        self.monthSumRadio = QtGui.QRadioButton(self.groupBox_6)
        self.monthSumRadio.setObjectName(_fromUtf8("monthSumRadio"))
        self.verticalLayout_2.addWidget(self.monthSumRadio)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.typeCombo = QtGui.QComboBox(self.groupBox_6)
        self.typeCombo.setObjectName(_fromUtf8("typeCombo"))
        self.horizontalLayout_12.addWidget(self.typeCombo)
        self.numCombo = QtGui.QComboBox(self.groupBox_6)
        self.numCombo.setObjectName(_fromUtf8("numCombo"))
        self.horizontalLayout_12.addWidget(self.numCombo)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_12)
        self.sumTypeCombo = QtGui.QComboBox(self.groupBox_6)
        self.sumTypeCombo.setObjectName(_fromUtf8("sumTypeCombo"))
        self.horizontalLayout_19.addWidget(self.sumTypeCombo)
        self.queryBtn_2 = QtGui.QPushButton(self.groupBox_6)
        self.queryBtn_2.setObjectName(_fromUtf8("queryBtn_2"))
        self.horizontalLayout_19.addWidget(self.queryBtn_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout_19)
        self.gridLayout_6.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.sumTableWidget = MyTable(self.groupBox_2)
        self.sumTableWidget.setObjectName(_fromUtf8("sumTableWidget"))
        self.verticalLayout_7.addWidget(self.sumTableWidget)
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.calcTableWidget = MyTable(self.groupBox_3)
        self.calcTableWidget.setObjectName(_fromUtf8("calcTableWidget"))
        self.gridLayout_7.addWidget(self.calcTableWidget, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.startDateEdit_3 = QtGui.QDateEdit(self.groupBox_5)
        self.startDateEdit_3.setCalendarPopup(True)
        self.startDateEdit_3.setObjectName(_fromUtf8("startDateEdit_3"))
        self.horizontalLayout_6.addWidget(self.startDateEdit_3)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.endDateEdit_3 = QtGui.QDateEdit(self.groupBox_5)
        self.endDateEdit_3.setDate(QtCore.QDate(2014, 1, 1))
        self.endDateEdit_3.setCalendarPopup(True)
        self.endDateEdit_3.setObjectName(_fromUtf8("endDateEdit_3"))
        self.horizontalLayout_6.addWidget(self.endDateEdit_3)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.cmpMethCombo = QtGui.QComboBox(self.groupBox_5)
        self.cmpMethCombo.setObjectName(_fromUtf8("cmpMethCombo"))
        self.horizontalLayout_5.addWidget(self.cmpMethCombo)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.cmpTypeCombo = QtGui.QComboBox(self.groupBox_5)
        self.cmpTypeCombo.setObjectName(_fromUtf8("cmpTypeCombo"))
        self.horizontalLayout_7.addWidget(self.cmpTypeCombo)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.smallValueEdit = QtGui.QLineEdit(self.groupBox_5)
        self.smallValueEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.smallValueEdit.setObjectName(_fromUtf8("smallValueEdit"))
        self.horizontalLayout_2.addWidget(self.smallValueEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.bigValueEdit = QtGui.QLineEdit(self.groupBox_5)
        self.bigValueEdit.setText(_fromUtf8(""))
        self.bigValueEdit.setObjectName(_fromUtf8("bigValueEdit"))
        self.horizontalLayout_3.addWidget(self.bigValueEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.calculateBtn = QtGui.QPushButton(self.groupBox_5)
        self.calculateBtn.setObjectName(_fromUtf8("calculateBtn"))
        self.horizontalLayout_10.addWidget(self.calculateBtn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_15 = QtGui.QLabel(self.groupBox_8)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout.addWidget(self.label_15)
        self.startDateEdit_4 = QtGui.QDateEdit(self.groupBox_8)
        self.startDateEdit_4.setCalendarPopup(True)
        self.startDateEdit_4.setObjectName(_fromUtf8("startDateEdit_4"))
        self.horizontalLayout.addWidget(self.startDateEdit_4)
        self.label_16 = QtGui.QLabel(self.groupBox_8)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout.addWidget(self.label_16)
        self.endDateEdit_4 = QtGui.QDateEdit(self.groupBox_8)
        self.endDateEdit_4.setDate(QtCore.QDate(2014, 1, 1))
        self.endDateEdit_4.setCalendarPopup(True)
        self.endDateEdit_4.setObjectName(_fromUtf8("endDateEdit_4"))
        self.horizontalLayout.addWidget(self.endDateEdit_4)
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout.addWidget(self.label_17)
        self.weightEdit = QtGui.QLineEdit(self.groupBox_8)
        self.weightEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.weightEdit.setObjectName(_fromUtf8("weightEdit"))
        self.horizontalLayout.addWidget(self.weightEdit)
        self.label_18 = QtGui.QLabel(self.groupBox_8)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout.addWidget(self.label_18)
        self.crossTypeCombo = QtGui.QComboBox(self.groupBox_8)
        self.crossTypeCombo.setObjectName(_fromUtf8("crossTypeCombo"))
        self.horizontalLayout.addWidget(self.crossTypeCombo)
        self.crossBtn = QtGui.QPushButton(self.groupBox_8)
        self.crossBtn.setObjectName(_fromUtf8("crossBtn"))
        self.horizontalLayout.addWidget(self.crossBtn)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout_9.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.crossTableWidget = MyTable(self.groupBox_7)
        self.crossTableWidget.setObjectName(_fromUtf8("crossTableWidget"))
        self.gridLayout_8.addWidget(self.crossTableWidget, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.horizontalLayout_20.addWidget(self.tabWidget)
        self.groupBox_9 = QtGui.QGroupBox(self.splitter_3)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.combineWidget = MyTable(self.groupBox_9)
        self.combineWidget.setObjectName(_fromUtf8("combineWidget"))
        self.gridLayout_10.addWidget(self.combineWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.splitter_3, 0, 1, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.showGroupBtn = QtGui.QPushButton(self.centralWidget)
        self.showGroupBtn.setMaximumSize(QtCore.QSize(100, 20))
        self.showGroupBtn.setCheckable(True)
        self.showGroupBtn.setObjectName(_fromUtf8("showGroupBtn"))
        self.horizontalLayout_17.addWidget(self.showGroupBtn)
        self.classifyBtn = QtGui.QPushButton(self.centralWidget)
        self.classifyBtn.setMaximumSize(QtCore.QSize(100, 20))
        self.classifyBtn.setCheckable(True)
        self.classifyBtn.setObjectName(_fromUtf8("classifyBtn"))
        self.horizontalLayout_17.addWidget(self.classifyBtn)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout_17, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1227, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_addGroup = QtGui.QAction(MainWindow)
        self.action_addGroup.setObjectName(_fromUtf8("action_addGroup"))
        self.action_editGroup = QtGui.QAction(MainWindow)
        self.action_editGroup.setObjectName(_fromUtf8("action_editGroup"))
        self.action_showGroupView = QtGui.QAction(MainWindow)
        self.action_showGroupView.setCheckable(True)
        self.action_showGroupView.setObjectName(_fromUtf8("action_showGroupView"))
        self.action_deleteGroup = QtGui.QAction(MainWindow)
        self.action_deleteGroup.setObjectName(_fromUtf8("action_deleteGroup"))
        self.menu_2.addAction(self.action)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "分组1", None))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "分组2", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(_translate("MainWindow", "原始数据筛选", None))
        self.label_2.setText(_translate("MainWindow", "开始日期：", None))
        self.label_3.setText(_translate("MainWindow", "结束日期：", None))
        self.queryBtn.setText(_translate("MainWindow", "查询", None))
        self.groupBox.setTitle(_translate("MainWindow", "原始数据：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "原始数据", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "n日和筛选", None))
        self.label_11.setText(_translate("MainWindow", "开始日期：", None))
        self.label_12.setText(_translate("MainWindow", "结束日期：", None))
        self.daySumRadio.setText(_translate("MainWindow", "日和", None))
        self.weekSumRadio.setText(_translate("MainWindow", "周和", None))
        self.monthSumRadio.setText(_translate("MainWindow", "月和", None))
        self.queryBtn_2.setText(_translate("MainWindow", "查询", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "n日数据", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "n日和", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "计算结果", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "计算筛选", None))
        self.label_4.setText(_translate("MainWindow", "比较日期：", None))
        self.label_7.setText(_translate("MainWindow", "——", None))
        self.label_6.setText(_translate("MainWindow", "比较方法", None))
        self.label_5.setText(_translate("MainWindow", "比较指标：", None))
        self.label_8.setText(_translate("MainWindow", "结果筛选：", None))
        self.label_9.setText(_translate("MainWindow", ">=", None))
        self.label_10.setText(_translate("MainWindow", "<=", None))
        self.calculateBtn.setText(_translate("MainWindow", "计算", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "自定义计算", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "跨区筛选", None))
        self.label_15.setText(_translate("MainWindow", "比较日期：", None))
        self.label_16.setText(_translate("MainWindow", "——", None))
        self.label_17.setText(_translate("MainWindow", "权重(%)：", None))
        self.label_18.setText(_translate("MainWindow", "指标：", None))
        self.crossBtn.setText(_translate("MainWindow", "跨区计算", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "跨区结果：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "跨区", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "拼接结果：", None))
        self.showGroupBtn.setText(_translate("MainWindow", "自选", None))
        self.classifyBtn.setText(_translate("MainWindow", "版块▲", None))
        self.menu.setTitle(_translate("MainWindow", "文件", None))
        self.menu_2.setTitle(_translate("MainWindow", "显示", None))
        self.action.setText(_translate("MainWindow", "设置列", None))
        self.action_addGroup.setText(_translate("MainWindow", "添加分组", None))
        self.action_editGroup.setText(_translate("MainWindow", "编辑分组", None))
        self.action_showGroupView.setText(_translate("MainWindow", "股票筛选", None))
        self.action_deleteGroup.setText(_translate("MainWindow", "删除分组", None))

from MyTable import MyTable

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

